/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './*.{ts,tsx,js,jsx}',
    './components/**/*.{ts,tsx,js,jsx}',
    './features/**/*.{ts,tsx,js,jsx}',
    './hooks/**/*.{ts,tsx,js,jsx}',
    './services/**/*.{ts,tsx,js,jsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        mono: ['"Fira Code"', 'monospace'],
        terminal: ['"VT323"', 'monospace'],
        display: ['"Space Grotesk"', 'sans-serif'],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
        xs: ['0.6875rem', { lineHeight: '1rem' }],
        sm: ['0.8125rem', { lineHeight: '1.25rem' }],
        base: ['0.9375rem', { lineHeight: '1.5rem' }],
        lg: ['1.0625rem', { lineHeight: '1.75rem' }],
        xl: ['1.1875rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.375rem', { lineHeight: '2rem' }],
        '3xl': ['1.625rem', { lineHeight: '2.125rem' }],
      },
      typography: {
        DEFAULT: {
          css: {
            '--tw-prose-body': 'rgb(var(--color-terminal-text))',
            '--tw-prose-headings': 'rgb(var(--color-terminal-text))',
            '--tw-prose-links': 'rgb(var(--color-terminal-text))',
            '--tw-prose-bold': 'rgb(var(--color-terminal-text))',
            '--tw-prose-code': 'rgb(var(--color-terminal-text))',
            '--tw-prose-quotes': 'rgb(var(--color-terminal-dim))',
            '--tw-prose-quote-borders': 'rgb(var(--color-terminal-dim))',
          },
        },
      },
      colors: {
        terminal: {
          bg: 'rgb(var(--color-terminal-bg) / <alpha-value>)',
          text: 'rgb(var(--color-terminal-text) / <alpha-value>)',
          dim: 'rgb(var(--color-terminal-dim) / <alpha-value>)',
          muted: 'rgb(var(--color-terminal-muted) / <alpha-value>)',
          alert: 'rgb(var(--color-terminal-alert) / <alpha-value>)',
          highlight: 'rgb(var(--color-terminal-highlight) / <alpha-value>)',
        },
      },
      boxShadow: {
        glow: 'var(--shadow-glow)',
        hard: '4px 4px 0px 0px rgb(var(--color-terminal-text) / 0.2)',
        'hard-lg': '8px 8px 0px 0px rgb(var(--color-terminal-text) / 0.15)',
      },
      animation: {
        'pulse-fast': 'pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        cursor: 'cursor .75s step-end infinite',
        'fade-in': 'fadeIn 0.3s ease-out',
        'glitch-1': 'glitch1 2s infinite linear alternate-reverse',
        'glitch-2': 'glitch2 3s infinite linear alternate-reverse',
        scanline: 'scanline 8s linear infinite',
        'spin-slow': 'spin 20s linear infinite',
        'border-flow': 'borderFlow 3s linear infinite',
        'border-flow-v': 'borderFlowV 4s linear infinite',
      },
      keyframes: {
        cursor: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(5px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        glitch1: {
          '0%': { clipPath: 'inset(20% 0 30% 0)' },
          '5%': { clipPath: 'inset(10% 0 85% 0)' },
          '10%': { clipPath: 'inset(40% 0 43% 0)' },
          '15%': { clipPath: 'inset(80% 0 5% 0)' },
          '20%': { clipPath: 'inset(10% 0 80% 0)' },
          '25%': { clipPath: 'inset(60% 0 15% 0)' },
          '30%': { clipPath: 'inset(30% 0 60% 0)' },
          '35%': { clipPath: 'inset(80% 0 5% 0)' },
          '40%': { clipPath: 'inset(10% 0 85% 0)' },
          '45%': { clipPath: 'inset(40% 0 43% 0)' },
          '50%': { clipPath: 'inset(20% 0 30% 0)' },
          '55%': { clipPath: 'inset(60% 0 15% 0)' },
          '60%': { clipPath: 'inset(10% 0 80% 0)' },
          '65%': { clipPath: 'inset(80% 0 5% 0)' },
          '70%': { clipPath: 'inset(30% 0 60% 0)' },
          '75%': { clipPath: 'inset(60% 0 15% 0)' },
          '80%': { clipPath: 'inset(20% 0 30% 0)' },
          '85%': { clipPath: 'inset(10% 0 85% 0)' },
          '90%': { clipPath: 'inset(40% 0 43% 0)' },
          '95%': { clipPath: 'inset(80% 0 5% 0)' },
          '100%': { clipPath: 'inset(10% 0 80% 0)' },
        },
        glitch2: {
          '0%': { clipPath: 'inset(10% 0 85% 0)' },
          '5%': { clipPath: 'inset(80% 0 5% 0)' },
          '10%': { clipPath: 'inset(20% 0 30% 0)' },
          '15%': { clipPath: 'inset(60% 0 15% 0)' },
          '20%': { clipPath: 'inset(30% 0 60% 0)' },
          '25%': { clipPath: 'inset(80% 0 5% 0)' },
          '30%': { clipPath: 'inset(10% 0 85% 0)' },
          '35%': { clipPath: 'inset(40% 0 43% 0)' },
          '40%': { clipPath: 'inset(20% 0 30% 0)' },
          '45%': { clipPath: 'inset(60% 0 15% 0)' },
          '50%': { clipPath: 'inset(10% 0 80% 0)' },
          '55%': { clipPath: 'inset(80% 0 5% 0)' },
          '60%': { clipPath: 'inset(30% 0 60% 0)' },
          '65%': { clipPath: 'inset(60% 0 15% 0)' },
          '70%': { clipPath: 'inset(20% 0 30% 0)' },
          '75%': { clipPath: 'inset(10% 0 85% 0)' },
          '80%': { clipPath: 'inset(40% 0 43% 0)' },
          '85%': { clipPath: 'inset(80% 0 5% 0)' },
          '90%': { clipPath: 'inset(10% 0 80% 0)' },
          '95%': { clipPath: 'inset(60% 0 15% 0)' },
          '100%': { clipPath: 'inset(30% 0 60% 0)' },
        },
        scanline: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(1000%)' },
        },
        borderFlow: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        borderFlowV: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
      },
    },
  },
  plugins: [],
};
